import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";
import User from "./User";

/**
 * EmailCode Model Attributes Interface
 * 
 * Defines the structure of an EmailCode record used for
 * email verification and password reset functionality.
 */
interface EmailCodeAttributes {
  id: number;
  code: string;
  user_id: number;
}

/**
 * EmailCode Creation Attributes Interface
 * 
 * Defines which fields are optional when creating a new EmailCode.
 * id: Auto-generated by the database
 */
interface EmailCodeCreationAttributes
  extends Optional<EmailCodeAttributes, "id"> {}

/**
 * EmailCode Model
 * 
 * Stores verification codes for email verification and password reset.
 * 
 * Features:
 * - Cryptographically secure random codes (32 bytes hex)
 * - Associated with a specific user (foreign key)
 * - Deleted after successful verification/reset
 * - Cascade deletion when user is deleted
 * - Used for both email verification and password reset flows
 * 
 * Usage:
 * 1. Email Verification: Generated when user registers
 * 2. Password Reset: Generated when user requests password reset
 */
class EmailCode
  extends Model<EmailCodeAttributes, EmailCodeCreationAttributes>
  implements EmailCodeAttributes
{
  public id!: number;
  public code!: string;
  public user_id!: number;

  public user?: User;

  // timestamps
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

EmailCode.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    code: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: User,
        key: "id",
      },
    },
  },
  {
    sequelize,
    tableName: "emailCode",
    timestamps: true,
  }
);

export default EmailCode;
