import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";
import EmailCode from "./EmailCode";

/**
 * User Model Attributes Interface
 *
 * Defines the structure of a User record in the database.
 */
interface UserAttributes {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  country: string;
  image: string;
  isVerify?: boolean;
}

/**
 * User Creation Attributes Interface
 *
 * Defines which fields are optional when creating a new User.
 * id: Auto-generated by the database
 * isVerify: Defaults to false if not provided
 */
interface UserCreationAttributes
  extends Optional<UserAttributes, "id" | "isVerify"> {}

/**
 * User Model
 *
 * Represents a user account in the authentication system.
 *
 * Features:
 * - Unique email addresses for authentication
 * - Secure password storage (hashed with bcrypt)
 * - Email verification status tracking
 * - Profile information (name, country, image)
 * - One-to-one relationship with EmailCode for verification
 * - Automatic timestamps (createdAt, updatedAt)
 */
class User
  extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes
{
  public id!: number;
  public first_name!: string;
  public last_name!: string;
  public email!: string;
  public password!: string;
  public country!: string;
  public image!: string;
  public isVerify!: boolean;

  public emailCode?: EmailCode;

  // timestamps
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

User.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    first_name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    last_name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    country: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    image: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    isVerify: {
      type: DataTypes.BOOLEAN,
      allowNull: true,
      defaultValue: false,
    },
  },
  {
    sequelize,
    tableName: "user",
    timestamps: true,
  }
);

export default User;
